### ISSUE TITLE
Stack trace behavior when "type":"module" missing from package.json

### ISSUE THREAD

**Issue by mindplay-dk** [esbuild-kit/tsx#103]
### Bug description

Unsure if this is supposed to work or not, but I ran into some odd behavior with source-maps and stack-traces, which behave quite differently when adding or removing `"type": "module"` from `package.json`.

The [bit that fails](https://github.com/mindplay-dk/inertion/blob/291d6a38181fdbd672afc760353b68ddad8d590f/src/harness.ts#L49-L51) is very simple:

```ts
        const location = new Error().stack!
          .split("\n")[2]
          .replace(/^\s+at /, "");
```

I've been using this without problems with `node` and `ts-node` for a while.

I tried adding a `console.log` to see what the `stack` property on the `Error` object looks like without or without the `"type": "module"` setting - looks like some stack-traces aren't resolving and some source references are `null` without `"module"`:

![image](https://user-images.githubusercontent.com/103348/193039452-e567f7cb-d476-4fd4-95f9-0450ed7bd902.png)

### Reproduction

Sample repo here:

https://github.com/mindplay-dk/try-tsx/compare/package-type

Check out the `package-type` branch and `npm run test`, which works.

Check out the `master` branch (or just remove `"type": "module"` from `package.json`) and for some reason the stack-trace doesn't behave like it normally does.

**This is not a big deal** - obviously I can just enable `"type": "module"` and everything is fine.

I just figured I'd try to help by providing this information in case it's useful and points to a problem. 🙂

(If `"type": "module"` *should* be enabled, perhaps all that's needed is a documentation tweak, or possibly an extra validation to stop others from getting into a situation with undefined behavior?)

### Environment

```shell
System:
    OS: Linux 5.10 Ubuntu 16.04.7 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 4.96 GB / 6.13 GB
    Container: Yes
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.4 - ~/.npm-global/bin/yarn
    npm: 8.5.5 - ~/.npm-global/bin/npm
  npmPackages:
    tsx: ^3.9.0 => 3.9.0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Please provide a **minimal** reproduction

**Comment by mindplay-dk** [comment]
Okay, I can strip the unused files and deps, and wittle it down to a `console.log` statement:

https://github.com/mindplay-dk/try-tsx/blob/minimal/src/test.ts

I don't know how to make it more minimal than that?

There needs to be an external package for this issue to arise.

Do you want me to create and publish a smaller package to make it more minimal than that? The amount of code being run from that package now is not a lot of lines - it's basically `run`, which [calls](https://github.com/mindplay-dk/inertion/blob/master/src/harness.ts#L25) `runTest`, which [picks up a stack trace](https://github.com/mindplay-dk/inertion/blob/291d6a38181fdbd672afc760353b68ddad8d590f/src/harness.ts#L49-L51).

**Comment by privatenumber** [comment]
A minimal reproduction would ideally be a code snippet. Your reproduction is not minimal because it has needless dependencies and a testing framework setup. The repo also seems to contain a server.

This might be a similar to this issue which contains a great example of a minimal reproduction: https://github.com/esbuild-kit/core-utils/issues/32 However, I'm not sure if it's the same issue because that issue is reporting the file path in the error stack is null, while yours seems to be fine.

I'm also not sure I understand the issue you're reporting. You mention that a `commonjs` type package contains `null.*` in the error stack, but your error stack for `module` type package also contains `null.*` on lines 4, 10, & 11.

**Comment by mindplay-dk** [comment]
> Your reproduction is not minimal because it has needless dependencies and a testing framework setup. The repo also seems to contain a server.

As said, I removed those from the `minimal` branch.

There is a little bit of the test framework setup left, but the problem occurs inside the test framework, where `new Error().stack` seems to be producing something "non standard" - that's the issue I'm trying to report. (my remark about nulls was probably wrong, please ignore that.)

It looks like source maps aren't being applied to the stack-trace, in that external package - it's producing a crazy long `"<around 9000 spaces> ^"` string, it's trying to point to the `new Error` call site, at a character offset in an extremely long line, inside the minified JS bundle.

I hacked a `console.log(new Error().stack)` statement into `node_modules/inertion/dist/index.js` to confirm that. 🙈

![image](https://user-images.githubusercontent.com/103348/193264191-83fccbc2-0b28-41bc-8549-cf5e264eb4d6.png)

If I put the same statement in the `node_modules/inertion/dist/index.mjs` file (which gets loaded when `"type":"module"` is set) the output looks as expected:

![image](https://user-images.githubusercontent.com/103348/193264685-522f2d50-f741-41b9-bf54-7c63c89eeeea.png)

I'm sorry, but I don't know how to create a minimal/isolated repro for this - it only seems to occur in the installed package...

**Comment by mindplay-dk** [comment]
The problem might not be the line length, but the actual formatting of the `stack` property.

If I do a `console.log` like this:

![image](https://user-images.githubusercontent.com/103348/193266899-d5c4a270-4c7c-4ca9-ae6a-6892b06700c4.png)

Here it's logged from a plain JS file with `"type":"module"`, using `import`:

![image](https://user-images.githubusercontent.com/103348/193266441-9c3405ea-ea04-470a-8d44-572730d2134d.png)

Here it's logged from a plain JS file without `"type":"module"`, using `require` instead of `import`:

![image](https://user-images.githubusercontent.com/103348/193266219-8db1b4fb-d221-46be-934a-f0cb2d0e7d16.png)

Note the absence of the file location and `"<spaces> ^ "` section - this doesn't normally occur in the `stack` property string - I think normally this string includes the stack trace only?

Now here's the output from `tsx` with `"type":"module"`:

![image](https://user-images.githubusercontent.com/103348/193267234-5c0b0994-3884-47d4-814c-2798f9e9ee68.png)

And here's the output from `tsx` without `"type":"module"`:

![image](https://user-images.githubusercontent.com/103348/193267366-6a2c9d65-0afc-4f92-bf36-5cd77bbb0b4b.png)

In both cases, there's those extra lines with the filename, the source line, and the `^` pointing to the call site.

I don't get those extra lines when running under plain `node`, under `ts-node`, or in a browser.

I think that's where the problem is.

Again, not sure how to isolate that in a minimal repro.

I looked around for a possible source of this issue, and it could be with `stack-utils` maybe? Not sure.

I guess, either way, this is technically a non-standard feature (?) so there's no spec I can point to and say "this is how it should work". Unfortunately, there currently no standardized API for stack traces, as far as I know, and this API appears to be what test frameworks rely on.

**Comment by privatenumber** [comment]
I'm going to close this one out because:
1. There's no minimal reproduction. Please remove any dependencies as that may be what's problematic.
2. There's too much to read for others to understand the problem (it's a lot of "thinking out loud"). Please boil it down to a simple "expected behavior" and a demonstration of how tsx diverges from that.

https://github.com/esbuild-kit/core-utils/issues/32 was fixed in https://github.com/esbuild-kit/tsx/releases/tag/v3.10.0. Please see if that works.

Otherwise, feel free to open a _new_ issue clearly and concisely communicating the problem.

**Comment by mindplay-dk** [comment]
Upgrading to `3.10.0` did not resolve the problem.

I've opened a new issue with a more concise description and reproduction in #114
